version: '3.8'

services:
  app:
    build: .
    container_name: backend3-proyecto-final-adoptme
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MODE=DEV
      - MONGO_DB_URL=mongodb+srv://arinocetti:mMlimyXD1EQrsjX8@cluster0.wnj5bbe.mongodb.net/
    restart: always
